# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90373047a1858bf662de156f0dbb970e40b8a7a3a8a65a78bb61fdab904173fa6a827e745104c887fe6db62a370a43f2be3fef8972bef5dee4b3a2a54f873d9

test:
  secret_key_base: 72aec520a3c48777adc12bccb37dfbcf616b97acbb55d76790d5bc67b1fba562bdcd75ae996e73c09fdc23408df7980ebdb0ab8087fddd3376c44f62af7456da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
